name: Option Alert

on:
  schedule:
    - cron: '0 4 * * *'  # 9:30 AM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install yfinance pandas

      - run: python alert.py
        env:
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
